# MySql数据源
spring:
  datasource:
    url: jdbc:mysql://47.76.131.61:3306/coin_info?useSSL=false&serverTimezone=UTC
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: messages
    encoding: UTF-8

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.coin.info.entity
  global-config:
    db-config:
      id-type: auto
