# MySql数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.168.131:3306/coin_info?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  messages:
    basename: messages
    encoding: UTF-8

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.coin.info.entity
  global-config:
    db-config:
      id-type: auto
